#################################################################################
# Copyright 2018 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#
# @author: Tingyu Zeng, Dell
# @version: 1.0.0
#################################################################################

# This is a TOML config file for edgexsecurity service.

title = "EdgeX security service config file"

[secretservice]
scheme = "https"
server = "127.0.0.1"
port = "8200"
certpath = "v1/secret/edgex/pki/tls/edgex-kong"
cafilepath = "/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem"
certfilepath = "/vault/config/pki/EdgeXFoundryCA/edgex-vault.pem"
keyfilepath = "/vault/config/pki/EdgeXFoundryCA/edgex-vault.priv.key"
vaultinitparm = "resp-init.json"
vaultsecretshares = 5
vaultsecretthreshold = 3
tokenfolderpath = "/vault/config/assets"
policypath4admin = "res/vault-policy-admin.hcl"
policyname4admin = "admin"
tokenname4admin = "admin"
policypath4kong = "res/vault-policy-kong.hcl"
policyname4kong = "kong"
tokenname4kong = "kong"
snis = "edgex.com"